language: node_js
node_js:
      - "9"
before_install: npm install && npm run build
script: 
    - sed -e "s#1931861#$PARTNER_ID#g" -e "s#83c3d4449a3abbe92ca5966f5f010eb4#$ADMIN_SECRET#g" -e "s#https://www.kaltura.com#https://www.kaltura.com#g" src/tests/tests-config.template.ts > src/tests/tests-config.ts
    - sed -e "s#1931861#$PARTNER_ID#g" -e "s#83c3d4449a3abbe92ca5966f5f010eb4#$ADMIN_SECRET#g" -e "s#https://www.kaltura.com#https://www.kaltura.com#g" -i src/tests/kaltura-request.spec.ts 
    - npm run test
notifications:
  email:
    recipients:
      - jess.portnoy@kaltura.com
      - eran.sakal@kaltura.com
      - amir.chervinsky@kaltura.com
    on_success: change
    on_failure: always
